package com.github.damontecres.stashapp.filter

import androidx.annotation.StringRes
import com.apollographql.apollo.api.Optional
import com.github.damontecres.stashapp.R
import com.github.damontecres.stashapp.api.type.CircumcisionCriterionInput
import com.github.damontecres.stashapp.api.type.CriterionModifier
import com.github.damontecres.stashapp.api.type.DateCriterionInput
import com.github.damontecres.stashapp.api.type.FloatCriterionInput
import com.github.damontecres.stashapp.api.type.GalleryFilterType
import com.github.damontecres.stashapp.api.type.GenderCriterionInput
import com.github.damontecres.stashapp.api.type.GroupFilterType
import com.github.damontecres.stashapp.api.type.HierarchicalMultiCriterionInput
import com.github.damontecres.stashapp.api.type.ImageFilterType
import com.github.damontecres.stashapp.api.type.IntCriterionInput
import com.github.damontecres.stashapp.api.type.MultiCriterionInput
import com.github.damontecres.stashapp.api.type.OrientationCriterionInput
import com.github.damontecres.stashapp.api.type.PerformerFilterType
import com.github.damontecres.stashapp.api.type.ResolutionCriterionInput
import com.github.damontecres.stashapp.api.type.SceneFilterType
import com.github.damontecres.stashapp.api.type.SceneMarkerFilterType
import com.github.damontecres.stashapp.api.type.StashDataFilter
import com.github.damontecres.stashapp.api.type.StringCriterionInput
import com.github.damontecres.stashapp.api.type.StudioFilterType
import com.github.damontecres.stashapp.api.type.TagFilterType
import com.github.damontecres.stashapp.data.DataType
import kotlin.reflect.KClass

/**
 * A way to filter a particular [DataType]
 *
 * @param name the key for the filter
 * @param nameStringId ID for human readable name
 * @param dataType the type of this sub-filter, not the overarching filter
 * @param type the type of this sub-filter
 * @param getter how to get the value of this from the filter
 * @param setter how to set the value of this on the filter (returning a copy)
 */
data class FilterOption<FilterType : StashDataFilter, ValueType : Any>(
    val name: String,
    @StringRes val nameStringId: Int,
    val dataType: DataType?,
    val type: KClass<ValueType>,
    val getter: (FilterType) -> Optional<ValueType?>,
    val setter: (FilterType, Optional<ValueType?>) -> FilterType,
    val allowedModifiers: List<CriterionModifier>? = null,
)

// Derived from files in https://github.com/stashapp/stash/tree/develop/ui/v2.5/src/models/list-filter/criteria
val MultiCriterionModifiers =
    listOf(
        CriterionModifier.INCLUDES_ALL,
        CriterionModifier.INCLUDES,
        CriterionModifier.EQUALS,
        CriterionModifier.IS_NULL,
        CriterionModifier.NOT_NULL,
    )
val PerformerTagsCriterionModifiers =
    listOf(
        CriterionModifier.INCLUDES_ALL,
        CriterionModifier.INCLUDES,
        CriterionModifier.IS_NULL,
        CriterionModifier.NOT_NULL,
    )
val StudiosCriterionModifiers =
    listOf(
        CriterionModifier.INCLUDES,
        CriterionModifier.IS_NULL,
        CriterionModifier.NOT_NULL,
    )
val RelationshipCriterionModifiers =
    listOf(
        CriterionModifier.INCLUDES,
        CriterionModifier.EXCLUDES,
        CriterionModifier.IS_NULL,
        CriterionModifier.NOT_NULL,
    )
val IncludesExcludesCriterionModifiers =
    listOf(
        CriterionModifier.INCLUDES_ALL,
        CriterionModifier.INCLUDES,
        CriterionModifier.EXCLUDES,
        CriterionModifier.IS_NULL,
        CriterionModifier.NOT_NULL,
    )

private val SceneFilterOptions =
    listOf(
        FilterOption<SceneFilterType, StringCriterionInput>(
            "audio_codec",
            R.string.stashapp_audio_codec,
            null,
            StringCriterionInput::class,
            { it.audio_codec },
            { filter, value -> filter.copy(audio_codec = value) },
        ),
        FilterOption<SceneFilterType, DateCriterionInput>(
            "date",
            R.string.stashapp_date,
            null,
            DateCriterionInput::class,
            { filter -> filter.date },
            { filter, value -> filter.copy(date = value) },
        ),
        FilterOption<SceneFilterType, StringCriterionInput>(
            "details",
            R.string.stashapp_details,
            null,
            StringCriterionInput::class,
            { it.details },
            { filter, value -> filter.copy(details = value) },
        ),
        FilterOption<SceneFilterType, IntCriterionInput>(
            "duration",
            R.string.stashapp_duration,
            null,
            IntCriterionInput::class,
            { it.duration },
            { filter, value -> filter.copy(duration = value) },
        ),
        FilterOption<SceneFilterType, StringCriterionInput>(
            "director",
            R.string.stashapp_director,
            null,
            StringCriterionInput::class,
            { it.director },
            { filter, value -> filter.copy(director = value) },
        ),
        FilterOption<SceneFilterType, HierarchicalMultiCriterionInput>(
            "groups",
            R.string.stashapp_groups,
            DataType.GROUP,
            HierarchicalMultiCriterionInput::class,
            { it.groups },
            { filter, value -> filter.copy(groups = value) },
            RelationshipCriterionModifiers,
        ),
        FilterOption<SceneFilterType, IntCriterionInput>(
            "o_counter",
            R.string.stashapp_o_counter,
            null,
            IntCriterionInput::class,
            { it.o_counter },
            { filter, value -> filter.copy(o_counter = value) },
        ),
        FilterOption<SceneFilterType, Boolean>(
            "organized",
            R.string.stashapp_organized,
            null,
            Boolean::class,
            { filter -> filter.organized },
            { filter, value -> filter.copy(organized = value) },
        ),
        FilterOption<SceneFilterType, IntCriterionInput>(
            "performer_age",
            R.string.stashapp_performer_age,
            null,
            IntCriterionInput::class,
            { it.performer_age },
            { filter, value -> filter.copy(performer_age = value) },
        ),
        FilterOption<SceneFilterType, IntCriterionInput>(
            "performer_count",
            R.string.stashapp_performer_count,
            null,
            IntCriterionInput::class,
            { it.performer_count },
            { filter, value -> filter.copy(performer_count = value) },
        ),
        FilterOption<SceneFilterType, Boolean>(
            "performer_favorite",
            R.string.stashapp_performer_favorite,
            null,
            Boolean::class,
            { it.performer_favorite },
            { filter, value -> filter.copy(performer_favorite = value) },
        ),
        FilterOption<SceneFilterType, HierarchicalMultiCriterionInput>(
            "performer_tags",
            R.string.stashapp_performer_tags,
            DataType.TAG,
            HierarchicalMultiCriterionInput::class,
            { filter -> filter.performer_tags },
            { filter, value -> filter.copy(performer_tags = value) },
            PerformerTagsCriterionModifiers,
        ),
        FilterOption<SceneFilterType, MultiCriterionInput>(
            "performers",
            R.string.stashapp_performers,
            DataType.PERFORMER,
            MultiCriterionInput::class,
            { it.performers },
            { filter, value -> filter.copy(performers = value) },
            MultiCriterionModifiers,
        ),
        FilterOption<SceneFilterType, IntCriterionInput>(
            "play_count",
            R.string.stashapp_play_count,
            null,
            IntCriterionInput::class,
            { it.play_count },
            { filter, value -> filter.copy(play_count = value) },
        ),
        FilterOption<SceneFilterType, IntCriterionInput>(
            "rating100",
            R.string.stashapp_rating,
            null,
            IntCriterionInput::class,
            { it.rating100 },
            { filter, value -> filter.copy(rating100 = value) },
        ),
        FilterOption<SceneFilterType, ResolutionCriterionInput>(
            "resolution",
            R.string.stashapp_resolution,
            null,
            ResolutionCriterionInput::class,
            { it.resolution },
            { filter, value -> filter.copy(resolution = value) },
        ),
        FilterOption<SceneFilterType, HierarchicalMultiCriterionInput>(
            "studios",
            R.string.stashapp_studios,
            DataType.STUDIO,
            HierarchicalMultiCriterionInput::class,
            { filter -> filter.studios },
            { filter, value -> filter.copy(studios = value) },
            StudiosCriterionModifiers,
        ),
        FilterOption<SceneFilterType, HierarchicalMultiCriterionInput>(
            "tags",
            R.string.stashapp_tags,
            DataType.TAG,
            HierarchicalMultiCriterionInput::class,
            { filter -> filter.tags },
            { filter, value -> filter.copy(tags = value) },
            MultiCriterionModifiers,
        ),
        FilterOption<SceneFilterType, IntCriterionInput>(
            "tag_count",
            R.string.stashapp_tag_count,
            null,
            IntCriterionInput::class,
            { it.tag_count },
            { filter, value -> filter.copy(tag_count = value) },
        ),
        FilterOption<SceneFilterType, StringCriterionInput>(
            "title",
            R.string.stashapp_title,
            null,
            StringCriterionInput::class,
            { it.title },
            { filter, value -> filter.copy(title = value) },
        ),
        FilterOption<SceneFilterType, StringCriterionInput>(
            "video_codec",
            R.string.stashapp_video_codec,
            null,
            StringCriterionInput::class,
            { it.video_codec },
            { filter, value -> filter.copy(video_codec = value) },
        ),
    )

private val PerformerFilterOptions =
    listOf(
        FilterOption<PerformerFilterType, IntCriterionInput>(
            "age",
            R.string.stashapp_age,
            null,
            IntCriterionInput::class,
            { filter -> filter.age },
            { filter, value -> filter.copy(age = value) },
        ),
        FilterOption<PerformerFilterType, StringCriterionInput>(
            "aliases",
            R.string.stashapp_aliases,
            null,
            StringCriterionInput::class,
            { it.aliases },
            { filter, value -> filter.copy(aliases = value) },
        ),
        FilterOption<PerformerFilterType, IntCriterionInput>(
            "birth_year",
            R.string.stashapp_birth_year,
            null,
            IntCriterionInput::class,
            { filter -> filter.birth_year },
            { filter, value -> filter.copy(birth_year = value) },
        ),
        FilterOption<PerformerFilterType, DateCriterionInput>(
            "birthdate",
            R.string.stashapp_birthdate,
            null,
            DateCriterionInput::class,
            { filter -> filter.birthdate },
            { filter, value -> filter.copy(birthdate = value) },
        ),
        FilterOption<PerformerFilterType, StringCriterionInput>(
            "country",
            R.string.stashapp_country,
            null,
            StringCriterionInput::class,
            { it.country },
            { filter, value -> filter.copy(country = value) },
        ),
        FilterOption<PerformerFilterType, CircumcisionCriterionInput>(
            "circumcised",
            R.string.stashapp_circumcised,
            null,
            CircumcisionCriterionInput::class,
            { filter -> filter.circumcised },
            { filter, value -> filter.copy(circumcised = value) },
        ),
        FilterOption<PerformerFilterType, IntCriterionInput>(
            "death_year",
            R.string.stashapp_death_year,
            null,
            IntCriterionInput::class,
            { filter -> filter.death_year },
            { filter, value -> filter.copy(death_year = value) },
        ),
        FilterOption<PerformerFilterType, DateCriterionInput>(
            "death_date",
            R.string.stashapp_death_date,
            null,
            DateCriterionInput::class,
            { filter -> filter.death_date },
            { filter, value -> filter.copy(death_date = value) },
        ),
        FilterOption<PerformerFilterType, StringCriterionInput>(
            "details",
            R.string.stashapp_details,
            null,
            StringCriterionInput::class,
            { it.details },
            { filter, value -> filter.copy(details = value) },
        ),
        FilterOption<PerformerFilterType, StringCriterionInput>(
            "ethnicity",
            R.string.stashapp_ethnicity,
            null,
            StringCriterionInput::class,
            { it.ethnicity },
            { filter, value -> filter.copy(ethnicity = value) },
        ),
        FilterOption<PerformerFilterType, StringCriterionInput>(
            "eye_color",
            R.string.stashapp_eye_color,
            null,
            StringCriterionInput::class,
            { it.eye_color },
            { filter, value -> filter.copy(eye_color = value) },
        ),
        FilterOption<PerformerFilterType, StringCriterionInput>(
            "fake_tits",
            R.string.stashapp_fake_tits,
            null,
            StringCriterionInput::class,
            { it.fake_tits },
            { filter, value -> filter.copy(fake_tits = value) },
        ),
        FilterOption<PerformerFilterType, Boolean>(
            "filter_favorites",
            R.string.stashapp_favourite,
            null,
            Boolean::class,
            { filter -> filter.filter_favorites },
            { filter, value -> filter.copy(filter_favorites = value) },
        ),
        FilterOption<PerformerFilterType, IntCriterionInput>(
            "gallery_count",
            R.string.stashapp_gallery_count,
            null,
            IntCriterionInput::class,
            { it.gallery_count },
            { filter, value -> filter.copy(gallery_count = value) },
        ),
        FilterOption<PerformerFilterType, GenderCriterionInput>(
            "gender",
            R.string.stashapp_gender,
            null,
            GenderCriterionInput::class,
            { it.gender },
            { filter, value -> filter.copy(gender = value) },
        ),
        FilterOption<PerformerFilterType, StringCriterionInput>(
            "hair_color",
            R.string.stashapp_hair_color,
            null,
            StringCriterionInput::class,
            { it.hair_color },
            { filter, value -> filter.copy(hair_color = value) },
        ),
        FilterOption<PerformerFilterType, IntCriterionInput>(
            "height",
            R.string.stashapp_height_cm,
            null,
            IntCriterionInput::class,
            { it.height_cm },
            { filter, value -> filter.copy(height_cm = value) },
        ),
        FilterOption<PerformerFilterType, IntCriterionInput>(
            "image_count",
            R.string.stashapp_image_count,
            null,
            IntCriterionInput::class,
            { it.image_count },
            { filter, value -> filter.copy(image_count = value) },
        ),
        FilterOption<PerformerFilterType, StringCriterionInput>(
            "measurements",
            R.string.stashapp_measurements,
            null,
            StringCriterionInput::class,
            { it.measurements },
            { filter, value -> filter.copy(measurements = value) },
        ),
        FilterOption<PerformerFilterType, StringCriterionInput>(
            "name",
            R.string.stashapp_name,
            null,
            StringCriterionInput::class,
            { it.name },
            { filter, value -> filter.copy(name = value) },
        ),
        FilterOption<PerformerFilterType, IntCriterionInput>(
            "o_counter",
            R.string.stashapp_o_counter,
            null,
            IntCriterionInput::class,
            { it.o_counter },
            { filter, value -> filter.copy(o_counter = value) },
        ),
        FilterOption<PerformerFilterType, StringCriterionInput>(
            "piercings",
            R.string.stashapp_piercings,
            null,
            StringCriterionInput::class,
            { it.piercings },
            { filter, value -> filter.copy(piercings = value) },
        ),
        FilterOption<PerformerFilterType, FloatCriterionInput>(
            "penis_length",
            R.string.stashapp_penis_length,
            null,
            FloatCriterionInput::class,
            { it.penis_length },
            { filter, value -> filter.copy(penis_length = value) },
        ),
        FilterOption<PerformerFilterType, IntCriterionInput>(
            "play_count",
            R.string.stashapp_play_count,
            null,
            IntCriterionInput::class,
            { it.play_count },
            { filter, value -> filter.copy(play_count = value) },
        ),
        FilterOption<PerformerFilterType, IntCriterionInput>(
            "rating100",
            R.string.stashapp_rating,
            null,
            IntCriterionInput::class,
            { it.rating100 },
            { filter, value -> filter.copy(rating100 = value) },
        ),
        FilterOption<PerformerFilterType, IntCriterionInput>(
            "scene_count",
            R.string.stashapp_scene_count,
            null,
            IntCriterionInput::class,
            { it.scene_count },
            { filter, value -> filter.copy(scene_count = value) },
        ),
        FilterOption<PerformerFilterType, HierarchicalMultiCriterionInput>(
            "studios",
            R.string.stashapp_studios,
            DataType.STUDIO,
            HierarchicalMultiCriterionInput::class,
            { filter -> filter.studios },
            { filter, value -> filter.copy(studios = value) },
            StudiosCriterionModifiers,
        ),
        FilterOption<PerformerFilterType, HierarchicalMultiCriterionInput>(
            "tags",
            R.string.stashapp_tags,
            DataType.TAG,
            HierarchicalMultiCriterionInput::class,
            { filter -> filter.tags },
            { filter, value -> filter.copy(tags = value) },
            MultiCriterionModifiers,
        ),
        FilterOption<PerformerFilterType, IntCriterionInput>(
            "tag_count",
            R.string.stashapp_tag_count,
            null,
            IntCriterionInput::class,
            { it.tag_count },
            { filter, value -> filter.copy(tag_count = value) },
        ),
        FilterOption<PerformerFilterType, StringCriterionInput>(
            "tattoos",
            R.string.stashapp_tattoos,
            null,
            StringCriterionInput::class,
            { it.tattoos },
            { filter, value -> filter.copy(tattoos = value) },
        ),
        FilterOption<PerformerFilterType, IntCriterionInput>(
            "weight",
            R.string.stashapp_weight,
            null,
            IntCriterionInput::class,
            { it.weight },
            { filter, value -> filter.copy(weight = value) },
        ),
    )

private val MarkerFilterOptions =
    listOf(
        FilterOption<SceneMarkerFilterType, MultiCriterionInput>(
            "performers",
            R.string.stashapp_performers,
            DataType.PERFORMER,
            MultiCriterionInput::class,
            { filter -> filter.performers },
            { filter, value -> filter.copy(performers = value) },
            MultiCriterionModifiers,
        ),
        FilterOption<SceneMarkerFilterType, DateCriterionInput>(
            "scene_date",
            R.string.stashapp_scene_date,
            null,
            DateCriterionInput::class,
            { filter -> filter.scene_date },
            { filter, value -> filter.copy(scene_date = value) },
        ),
        FilterOption<SceneMarkerFilterType, HierarchicalMultiCriterionInput>(
            "scene_tags",
            R.string.stashapp_scene_tags,
            DataType.TAG,
            HierarchicalMultiCriterionInput::class,
            { filter -> filter.scene_tags },
            { filter, value -> filter.copy(scene_tags = value) },
            MultiCriterionModifiers,
        ),
        FilterOption<SceneMarkerFilterType, HierarchicalMultiCriterionInput>(
            "tags",
            R.string.stashapp_tags,
            DataType.TAG,
            HierarchicalMultiCriterionInput::class,
            { filter -> filter.tags },
            { filter, value -> filter.copy(tags = value) },
            MultiCriterionModifiers,
        ),
    )

private val ImageFilterOptions =
    listOf(
        FilterOption<ImageFilterType, DateCriterionInput>(
            "date",
            R.string.stashapp_date,
            null,
            DateCriterionInput::class,
            { filter -> filter.date },
            { filter, value -> filter.copy(date = value) },
        ),
        FilterOption<ImageFilterType, StringCriterionInput>(
            "details",
            R.string.stashapp_details,
            null,
            StringCriterionInput::class,
            { it.details },
            { filter, value -> filter.copy(details = value) },
        ),
        FilterOption<ImageFilterType, MultiCriterionInput>(
            "galleries",
            R.string.stashapp_galleries,
            DataType.GALLERY,
            MultiCriterionInput::class,
            { filter -> filter.galleries },
            { filter, value -> filter.copy(galleries = value) },
            IncludesExcludesCriterionModifiers,
        ),
        FilterOption<ImageFilterType, IntCriterionInput>(
            "o_counter",
            R.string.stashapp_o_counter,
            null,
            IntCriterionInput::class,
            { it.o_counter },
            { filter, value -> filter.copy(o_counter = value) },
        ),
        FilterOption<ImageFilterType, OrientationCriterionInput>(
            "orientation",
            R.string.stashapp_orientation,
            null,
            OrientationCriterionInput::class,
            { it.orientation },
            { filter, value -> filter.copy(orientation = value) },
        ),
        FilterOption<ImageFilterType, IntCriterionInput>(
            "performer_age",
            R.string.stashapp_performer_age,
            null,
            IntCriterionInput::class,
            { it.performer_age },
            { filter, value -> filter.copy(performer_age = value) },
        ),
        FilterOption<ImageFilterType, IntCriterionInput>(
            "performer_count",
            R.string.stashapp_performer_count,
            null,
            IntCriterionInput::class,
            { it.performer_count },
            { filter, value -> filter.copy(performer_count = value) },
        ),
        FilterOption<ImageFilterType, Boolean>(
            "performer_favorite",
            R.string.stashapp_performer_favorite,
            null,
            Boolean::class,
            { it.performer_favorite },
            { filter, value -> filter.copy(performer_favorite = value) },
        ),
        FilterOption<ImageFilterType, HierarchicalMultiCriterionInput>(
            "performer_tags",
            R.string.stashapp_performer_tags,
            DataType.TAG,
            HierarchicalMultiCriterionInput::class,
            { filter -> filter.performer_tags },
            { filter, value -> filter.copy(performer_tags = value) },
            PerformerTagsCriterionModifiers,
        ),
        FilterOption<ImageFilterType, MultiCriterionInput>(
            "performers",
            R.string.stashapp_performers,
            DataType.PERFORMER,
            MultiCriterionInput::class,
            { filter -> filter.performers },
            { filter, value -> filter.copy(performers = value) },
            MultiCriterionModifiers,
        ),
        FilterOption<ImageFilterType, StringCriterionInput>(
            "photographer",
            R.string.stashapp_photographer,
            null,
            StringCriterionInput::class,
            { it.photographer },
            { filter, value -> filter.copy(photographer = value) },
        ),
        FilterOption<ImageFilterType, IntCriterionInput>(
            "rating100",
            R.string.stashapp_rating,
            null,
            IntCriterionInput::class,
            { it.rating100 },
            { filter, value -> filter.copy(rating100 = value) },
        ),
        FilterOption<ImageFilterType, ResolutionCriterionInput>(
            "resolution",
            R.string.stashapp_resolution,
            null,
            ResolutionCriterionInput::class,
            { it.resolution },
            { filter, value -> filter.copy(resolution = value) },
        ),
        FilterOption<ImageFilterType, HierarchicalMultiCriterionInput>(
            "studios",
            R.string.stashapp_studios,
            DataType.STUDIO,
            HierarchicalMultiCriterionInput::class,
            { filter -> filter.studios },
            { filter, value -> filter.copy(studios = value) },
            StudiosCriterionModifiers,
        ),
        FilterOption<ImageFilterType, HierarchicalMultiCriterionInput>(
            "tags",
            R.string.stashapp_tags,
            DataType.TAG,
            HierarchicalMultiCriterionInput::class,
            { filter -> filter.tags },
            { filter, value -> filter.copy(tags = value) },
            MultiCriterionModifiers,
        ),
        FilterOption<ImageFilterType, IntCriterionInput>(
            "tag_count",
            R.string.stashapp_tag_count,
            null,
            IntCriterionInput::class,
            { it.tag_count },
            { filter, value -> filter.copy(tag_count = value) },
        ),
        FilterOption<ImageFilterType, StringCriterionInput>(
            "title",
            R.string.stashapp_title,
            null,
            StringCriterionInput::class,
            { it.title },
            { filter, value -> filter.copy(title = value) },
        ),
    )

private val GalleryFilterOptions =
    listOf(
        FilterOption<GalleryFilterType, ResolutionCriterionInput>(
            "average_resolution",
            R.string.stashapp_average_resolution,
            null,
            ResolutionCriterionInput::class,
            { it.average_resolution },
            { filter, value -> filter.copy(average_resolution = value) },
        ),
        FilterOption<GalleryFilterType, DateCriterionInput>(
            "date",
            R.string.stashapp_date,
            null,
            DateCriterionInput::class,
            { filter -> filter.date },
            { filter, value -> filter.copy(date = value) },
        ),
        FilterOption<GalleryFilterType, StringCriterionInput>(
            "details",
            R.string.stashapp_details,
            null,
            StringCriterionInput::class,
            { it.details },
            { filter, value -> filter.copy(details = value) },
        ),
        FilterOption<GalleryFilterType, IntCriterionInput>(
            "image_count",
            R.string.stashapp_image_count,
            null,
            IntCriterionInput::class,
            { it.image_count },
            { filter, value -> filter.copy(image_count = value) },
        ),
        FilterOption<GalleryFilterType, IntCriterionInput>(
            "performer_age",
            R.string.stashapp_performer_age,
            null,
            IntCriterionInput::class,
            { it.performer_age },
            { filter, value -> filter.copy(performer_age = value) },
        ),
        FilterOption<GalleryFilterType, IntCriterionInput>(
            "performer_count",
            R.string.stashapp_performer_count,
            null,
            IntCriterionInput::class,
            { it.performer_count },
            { filter, value -> filter.copy(performer_count = value) },
        ),
        FilterOption<GalleryFilterType, Boolean>(
            "performer_favorite",
            R.string.stashapp_performer_favorite,
            null,
            Boolean::class,
            { it.performer_favorite },
            { filter, value -> filter.copy(performer_favorite = value) },
        ),
        FilterOption<GalleryFilterType, HierarchicalMultiCriterionInput>(
            "performer_tags",
            R.string.stashapp_performer_tags,
            DataType.TAG,
            HierarchicalMultiCriterionInput::class,
            { filter -> filter.performer_tags },
            { filter, value -> filter.copy(performer_tags = value) },
            PerformerTagsCriterionModifiers,
        ),
        FilterOption<GalleryFilterType, MultiCriterionInput>(
            "performers",
            R.string.stashapp_performers,
            DataType.PERFORMER,
            MultiCriterionInput::class,
            { filter -> filter.performers },
            { filter, value -> filter.copy(performers = value) },
            MultiCriterionModifiers,
        ),
        FilterOption<GalleryFilterType, StringCriterionInput>(
            "photographer",
            R.string.stashapp_photographer,
            null,
            StringCriterionInput::class,
            { it.photographer },
            { filter, value -> filter.copy(photographer = value) },
        ),
        FilterOption<GalleryFilterType, IntCriterionInput>(
            "rating100",
            R.string.stashapp_rating,
            null,
            IntCriterionInput::class,
            { it.rating100 },
            { filter, value -> filter.copy(rating100 = value) },
        ),
        FilterOption<GalleryFilterType, MultiCriterionInput>(
            "scenes",
            R.string.stashapp_scenes,
            DataType.SCENE,
            MultiCriterionInput::class,
            { filter -> filter.scenes },
            { filter, value -> filter.copy(scenes = value) },
            IncludesExcludesCriterionModifiers,
        ),
        FilterOption<GalleryFilterType, HierarchicalMultiCriterionInput>(
            "studios",
            R.string.stashapp_studios,
            DataType.STUDIO,
            HierarchicalMultiCriterionInput::class,
            { filter -> filter.studios },
            { filter, value -> filter.copy(studios = value) },
            StudiosCriterionModifiers,
        ),
        FilterOption<GalleryFilterType, HierarchicalMultiCriterionInput>(
            "tags",
            R.string.stashapp_tags,
            DataType.TAG,
            HierarchicalMultiCriterionInput::class,
            { filter -> filter.tags },
            { filter, value -> filter.copy(tags = value) },
            MultiCriterionModifiers,
        ),
        FilterOption<GalleryFilterType, StringCriterionInput>(
            "title",
            R.string.stashapp_title,
            null,
            StringCriterionInput::class,
            { it.title },
            { filter, value -> filter.copy(title = value) },
        ),
    )

private val TagFilterOptions =
    listOf(
        FilterOption<TagFilterType, StringCriterionInput>(
            "aliases",
            R.string.stashapp_aliases,
            null,
            StringCriterionInput::class,
            { it.aliases },
            { filter, value -> filter.copy(aliases = value) },
        ),
        FilterOption<TagFilterType, StringCriterionInput>(
            "description",
            R.string.stashapp_description,
            null,
            StringCriterionInput::class,
            { it.description },
            { filter, value -> filter.copy(description = value) },
        ),
        FilterOption<TagFilterType, Boolean>(
            "favorite",
            R.string.stashapp_favourite,
            null,
            Boolean::class,
            { filter -> filter.favorite },
            { filter, value -> filter.copy(favorite = value) },
        ),
        FilterOption<TagFilterType, IntCriterionInput>(
            "image_count",
            R.string.stashapp_image_count,
            null,
            IntCriterionInput::class,
            { it.image_count },
            { filter, value -> filter.copy(image_count = value) },
        ),
        FilterOption<TagFilterType, StringCriterionInput>(
            "name",
            R.string.stashapp_name,
            null,
            StringCriterionInput::class,
            { it.name },
            { filter, value -> filter.copy(name = value) },
        ),
        FilterOption<TagFilterType, IntCriterionInput>(
            "scene_count",
            R.string.stashapp_scene_count,
            null,
            IntCriterionInput::class,
            { it.scene_count },
            { filter, value -> filter.copy(scene_count = value) },
        ),
        FilterOption<TagFilterType, IntCriterionInput>(
            "studio_count",
            R.string.stashapp_studio_count,
            null,
            IntCriterionInput::class,
            { it.studio_count },
            { filter, value -> filter.copy(studio_count = value) },
        ),
        FilterOption<TagFilterType, IntCriterionInput>(
            "gallery_count",
            R.string.stashapp_gallery_count,
            null,
            IntCriterionInput::class,
            { it.gallery_count },
            { filter, value -> filter.copy(gallery_count = value) },
        ),
        FilterOption<TagFilterType, IntCriterionInput>(
            "marker_count",
            R.string.stashapp_marker_count,
            null,
            IntCriterionInput::class,
            { it.marker_count },
            { filter, value -> filter.copy(marker_count = value) },
        ),
        FilterOption<TagFilterType, IntCriterionInput>(
            "performer_count",
            R.string.stashapp_performer_count,
            null,
            IntCriterionInput::class,
            { it.performer_count },
            { filter, value -> filter.copy(performer_count = value) },
        ),
        FilterOption<TagFilterType, IntCriterionInput>(
            "parent_count",
            R.string.stashapp_parent_tag_count,
            null,
            IntCriterionInput::class,
            { it.parent_count },
            { filter, value -> filter.copy(parent_count = value) },
        ),
        FilterOption<TagFilterType, IntCriterionInput>(
            "child_count",
            R.string.stashapp_sub_tag_count,
            null,
            IntCriterionInput::class,
            { it.child_count },
            { filter, value -> filter.copy(child_count = value) },
        ),
        FilterOption<TagFilterType, HierarchicalMultiCriterionInput>(
            "parents",
            R.string.stashapp_parent_tags,
            DataType.TAG,
            HierarchicalMultiCriterionInput::class,
            { filter -> filter.parents },
            { filter, value -> filter.copy(parents = value) },
            MultiCriterionModifiers,
        ),
        FilterOption<TagFilterType, HierarchicalMultiCriterionInput>(
            "children",
            R.string.stashapp_sub_tags,
            DataType.TAG,
            HierarchicalMultiCriterionInput::class,
            { filter -> filter.children },
            { filter, value -> filter.copy(children = value) },
            MultiCriterionModifiers,
        ),
    )

private val StudioFilterOptions =
    listOf(
        FilterOption<StudioFilterType, StringCriterionInput>(
            "aliases",
            R.string.stashapp_aliases,
            null,
            StringCriterionInput::class,
            { it.aliases },
            { filter, value -> filter.copy(aliases = value) },
        ),
        FilterOption<StudioFilterType, StringCriterionInput>(
            "details",
            R.string.stashapp_details,
            null,
            StringCriterionInput::class,
            { it.details },
            { filter, value -> filter.copy(details = value) },
        ),
        FilterOption<StudioFilterType, Boolean>(
            "favorite",
            R.string.stashapp_favourite,
            null,
            Boolean::class,
            { filter -> filter.favorite },
            { filter, value -> filter.copy(favorite = value) },
        ),
        FilterOption<StudioFilterType, IntCriterionInput>(
            "image_count",
            R.string.stashapp_image_count,
            null,
            IntCriterionInput::class,
            { it.image_count },
            { filter, value -> filter.copy(image_count = value) },
        ),
        FilterOption<StudioFilterType, IntCriterionInput>(
            "gallery_count",
            R.string.stashapp_gallery_count,
            null,
            IntCriterionInput::class,
            { it.gallery_count },
            { filter, value -> filter.copy(gallery_count = value) },
        ),
        FilterOption<StudioFilterType, StringCriterionInput>(
            "name",
            R.string.stashapp_name,
            null,
            StringCriterionInput::class,
            { it.name },
            { filter, value -> filter.copy(name = value) },
        ),
        FilterOption<StudioFilterType, MultiCriterionInput>(
            "parents",
            R.string.stashapp_parent_studios,
            DataType.STUDIO,
            MultiCriterionInput::class,
            { filter -> filter.parents },
            { filter, value -> filter.copy(parents = value) },
            RelationshipCriterionModifiers,
        ),
        FilterOption<StudioFilterType, IntCriterionInput>(
            "rating100",
            R.string.stashapp_rating,
            null,
            IntCriterionInput::class,
            { it.rating100 },
            { filter, value -> filter.copy(rating100 = value) },
        ),
        FilterOption<StudioFilterType, IntCriterionInput>(
            "scene_count",
            R.string.stashapp_scene_count,
            null,
            IntCriterionInput::class,
            { it.scene_count },
            { filter, value -> filter.copy(scene_count = value) },
        ),
        FilterOption<StudioFilterType, IntCriterionInput>(
            "child_count",
            R.string.stashapp_subsidiary_studio_count,
            null,
            IntCriterionInput::class,
            { it.child_count },
            { filter, value -> filter.copy(child_count = value) },
        ),
        FilterOption<StudioFilterType, HierarchicalMultiCriterionInput>(
            "tags",
            R.string.stashapp_tags,
            DataType.TAG,
            HierarchicalMultiCriterionInput::class,
            { filter -> filter.tags },
            { filter, value -> filter.copy(tags = value) },
            MultiCriterionModifiers,
        ),
        FilterOption<StudioFilterType, IntCriterionInput>(
            "tag_count",
            R.string.stashapp_tag_count,
            null,
            IntCriterionInput::class,
            { it.tag_count },
            { filter, value -> filter.copy(tag_count = value) },
        ),
    )

private val GroupFilterOptions =
    listOf(
        FilterOption<GroupFilterType, HierarchicalMultiCriterionInput>(
            "containing_groups",
            R.string.stashapp_containing_groups,
            DataType.GROUP,
            HierarchicalMultiCriterionInput::class,
            { filter -> filter.containing_groups },
            { filter, value -> filter.copy(containing_groups = value) },
            RelationshipCriterionModifiers,
        ),
        FilterOption<GroupFilterType, IntCriterionInput>(
            "containing_group_count",
            R.string.stashapp_containing_group_count,
            null,
            IntCriterionInput::class,
            { it.containing_group_count },
            { filter, value -> filter.copy(containing_group_count = value) },
        ),
        FilterOption<GroupFilterType, DateCriterionInput>(
            "date",
            R.string.stashapp_date,
            null,
            DateCriterionInput::class,
            { filter -> filter.date },
            { filter, value -> filter.copy(date = value) },
        ),
        FilterOption<GroupFilterType, StringCriterionInput>(
            "director",
            R.string.stashapp_director,
            null,
            StringCriterionInput::class,
            { it.director },
            { filter, value -> filter.copy(director = value) },
        ),
        FilterOption<GroupFilterType, StringCriterionInput>(
            "name",
            R.string.stashapp_name,
            null,
            StringCriterionInput::class,
            { it.name },
            { filter, value -> filter.copy(name = value) },
        ),
        FilterOption<GroupFilterType, MultiCriterionInput>(
            "performers",
            R.string.stashapp_performers,
            DataType.PERFORMER,
            MultiCriterionInput::class,
            { it.performers },
            { filter, value -> filter.copy(performers = value) },
            MultiCriterionModifiers,
        ),
        FilterOption<GroupFilterType, IntCriterionInput>(
            "rating100",
            R.string.stashapp_rating,
            null,
            IntCriterionInput::class,
            { it.rating100 },
            { filter, value -> filter.copy(rating100 = value) },
        ),
        FilterOption<GroupFilterType, HierarchicalMultiCriterionInput>(
            "studios",
            R.string.stashapp_studios,
            DataType.STUDIO,
            HierarchicalMultiCriterionInput::class,
            { filter -> filter.studios },
            { filter, value -> filter.copy(studios = value) },
            StudiosCriterionModifiers,
        ),
        FilterOption<GroupFilterType, HierarchicalMultiCriterionInput>(
            "sub_groups",
            R.string.stashapp_sub_groups,
            DataType.GROUP,
            HierarchicalMultiCriterionInput::class,
            { filter -> filter.sub_groups },
            { filter, value -> filter.copy(sub_groups = value) },
            RelationshipCriterionModifiers,
        ),
        FilterOption<GroupFilterType, IntCriterionInput>(
            "sub_group_count",
            R.string.stashapp_sub_group_count,
            null,
            IntCriterionInput::class,
            { it.sub_group_count },
            { filter, value -> filter.copy(sub_group_count = value) },
        ),
        FilterOption<GroupFilterType, StringCriterionInput>(
            "synopsis",
            R.string.stashapp_synopsis,
            null,
            StringCriterionInput::class,
            { it.synopsis },
            { filter, value -> filter.copy(synopsis = value) },
        ),
        FilterOption<GroupFilterType, HierarchicalMultiCriterionInput>(
            "tags",
            R.string.stashapp_tags,
            DataType.TAG,
            HierarchicalMultiCriterionInput::class,
            { filter -> filter.tags },
            { filter, value -> filter.copy(tags = value) },
            MultiCriterionModifiers,
        ),
        FilterOption<GroupFilterType, IntCriterionInput>(
            "tag_count",
            R.string.stashapp_tag_count,
            null,
            IntCriterionInput::class,
            { it.tag_count },
            { filter, value -> filter.copy(tag_count = value) },
        ),
    )

val FilterOptions =
    mapOf(
        DataType.SCENE to SceneFilterOptions,
        DataType.PERFORMER to PerformerFilterOptions,
        DataType.MARKER to MarkerFilterOptions,
        DataType.IMAGE to ImageFilterOptions,
        DataType.GALLERY to GalleryFilterOptions,
        DataType.TAG to TagFilterOptions,
        DataType.STUDIO to StudioFilterOptions,
        DataType.GROUP to GroupFilterOptions,
    )

fun getFilterOptions(dataType: DataType): List<FilterOption<out StashDataFilter, out Any>> =
    FilterOptions[dataType] ?: throw UnsupportedOperationException("$dataType")
