name: "Bug Report"
description: Report a bug
title: "[BUG] - <title>"
labels: [
  "bug"
]
body:
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: Please enter a description of the bug
    validations:
      required: true
  - type: textarea
    id: reprod
    attributes:
      label: "Reproduction steps"
      description: Please enter the steps to reproduce
      value: |
        1. Click on '...'
        2. Scroll to '....'
        3. See error
      render: bash
    validations:
      required: false
  - type: input
    id: server
    attributes:
      label: "Server Version"
      description: What version of the server?
      placeholder: "v0.25.1"
    validations:
      required: true
  - type: input
    id: device
    attributes:
      label: "Device"
      description: What device are you using?
      placeholder: "NVIDIA Shield TV Pro 2019"
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: "Logs"
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: bash
    validations:
      required: false
