package com.github.damontecres.stashapp.util

val THIRD_PARTY_TAGS =
    listOf(
        "libc:F",
        "ExoPlayerImpl:W",
        // FireTV
        "Codec2Client:W",
        "CCodecBuffers:W",
        "CCodecConfig:W",
        "okhttp.Http2:I",
        "okhttp.TaskRunner:I",
        "LruBitmapPool:I",
        "FragmentManager:I",
        "ConfigStore:I",
        "GlideRequest:I",
        "FactoryPools:I",
        "ViewTarget:I",
        "Engine:I",
        "Downsampler:I",
        "TransformationUtils:I",
        "DecodeJob:I",
        "BufferPoolAccessor2.0:I",
        "ExifInterface:I",
        "MediaCodec:I",
        "SurfaceUtils:I",
        "ByteArrayPool:I",
        "HardwareConfig:I",
        "DfltImageHeaderParser:I",
    )

// TODO Add a method to auto generating this
// rg 'TAG = "(\w+)"' app/src/main/java/com/github/damontecres/stashapp/ -or '$1' --no-filename -N | sort | uniq | while read -r tag; do echo -n "\"$tag:V\","; done
val LOGCAT_TAGS =
    listOf(
        "ActionPresenter:V",
        "AppUpgradeHandler:V",
        "CardPresenter:V",
        "CodecSupport:V",
        "Constants:V",
        "CrashReportSenderFactory:V",
        "FilterListActivity:V",
        "FilterParser:V",
        "GalleryPresenter:V",
        "ImageActivity:V",
        "ImageGridClickedListener:V",
        "ImagePresenter:V",
        "MainFragment:V",
        "MainPageParser:V",
        "MarkerDetailsFragment:V",
        "MarkerPresenter:V",
        "MutationEngine:V",
        "PerformerFragment:V",
        "PinActivity:V",
        "PlaybackActivity:V",
        "PlaybackExoFragment:V",
        "PlaybackFragment:V",
        "PlaybackMarkersFragment:V",
        "QueryEngine:V",
        "ScenePresenter:V",
        "SearchForFragment:V",
        "ServerPreferences:V",
        "SettingsFragment:V",
        "SetupStep5Ssl:V",
        "StashApplication:V",
        "StashClient:V",
        "StashCoroutineExceptionHandler:V",
        "StashFilterPager:V",
        "StashFilterPresenter:V",
        "StashGlide:V",
        "StashGridFragment:V",
        "StashImageCardView:V",
        "StashItemViewClickListener:V",
        "StashPlayerView:V",
        "StashPresenter:V",
        "StashPreviewLoader:V",
        "StashSearchFragment:V",
        "StudioPresenter:V",
        "TagPresenter:V",
        "UpdateBroadcastReceiver:V",
        "UpdateChecker:V",
        "VideoDetailsFragment:V",
    )
